--------------------------------------------------------
--  File created - Tuesday-October-27-2009   
--------------------------------------------------------
  DROP TABLE "TESTUSER3"."ACCOUNT" cascade constraints;
  DROP TABLE "TESTUSER3"."ACCOUNT_TYPE" cascade constraints;
  DROP TABLE "TESTUSER3"."ADDRESS" cascade constraints;
  DROP TABLE "TESTUSER3"."ADDRESS_TYPE" cascade constraints;
  DROP TABLE "TESTUSER3"."BANK" cascade constraints;
  DROP TABLE "TESTUSER3"."BRANCH" cascade constraints;
  DROP TABLE "TESTUSER3"."CUSTOMER" cascade constraints;
  DROP TABLE "TESTUSER3"."CUSTOMER_SERVICE_REQUEST" cascade constraints;
  DROP TABLE "TESTUSER3"."CUSTOMER_TYPE" cascade constraints;
  DROP TABLE "TESTUSER3"."LOG_BOOK" cascade constraints;
  DROP TABLE "TESTUSER3"."SERVICE" cascade constraints;
  DROP TABLE "TESTUSER3"."SERVICE_REQUEST_OUTCOME" cascade constraints;
  DROP TABLE "TESTUSER3"."STAFF" cascade constraints;
  DROP TABLE "TESTUSER3"."STAFF_TYPE" cascade constraints;
  DROP TABLE "TESTUSER3"."TRANSACTION" cascade constraints;
  DROP TABLE "TESTUSER3"."TRANSACTION_TYPE" cascade constraints;
--------------------------------------------------------
--  DDL for Table ACCOUNT_TYPE
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."ACCOUNT_TYPE" 
   (	"ACCOUNT_TYPE_ID" VARCHAR2(20 BYTE), 
	"OVERDRAF_LIMIT" NUMBER(5,0), 
	"OTHER_DETAIL" VARCHAR2(100 BYTE), 
	"INTEREST_RATE" NUMBER(5,0), 
	"ACCOUNT_DESC" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."STAFF" 
   (	"STAFF_ID" VARCHAR2(20 BYTE), 
	"STAFF_TYPE_ID_FK" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"BIRTH_DATE" DATE, 
	"PHONE" VARCHAR2(20 BYTE), 
	"OTHER_DETAIL" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."ACCOUNT" 
   (	"ACCOUNT_ID" VARCHAR2(20 BYTE), 
	"BRANCH_SORTCODE_FK" VARCHAR2(20 BYTE), 
	"ACCOUNT_TYPE_ID_FK" VARCHAR2(20 BYTE), 
	"STAFF_ID_FK" VARCHAR2(20 BYTE), 
	"ACCOUNT_NAME" VARCHAR2(20 BYTE), 
	"BALANCE" NUMBER, 
	"DATE_OPENED" DATE, 
	"DATE_CLOSED" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADDRESS_TYPE
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."ADDRESS_TYPE" 
   (	"ADDRESS_TYPE_ID" VARCHAR2(20 BYTE), 
	"ADDRESS_TYPE_DESC" VARCHAR2(50 BYTE), 
	"OTHER_DETAIL" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BANK
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."BANK" 
   (	"BANK_ID" VARCHAR2(20 BYTE), 
	"BANK_NAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."CUSTOMER" 
   (	"CUSTOMER_ID" VARCHAR2(20 BYTE), 
	"CUSTOMER_TYPE_ID" VARCHAR2(20 BYTE), 
	"SSN" VARCHAR2(20 BYTE), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"BIRTH_DATE" DATE, 
	"EMAIL" VARCHAR2(40 BYTE), 
	"DATE_JOIN" DATE, 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."ADDRESS" 
   (	"ADDRESS_ID" VARCHAR2(20 BYTE), 
	"ADDRESS_TYPE_ID_FK" VARCHAR2(20 BYTE), 
	"BANK_ID_FK" VARCHAR2(20 BYTE), 
	"CUSTOMER_ID_FK" VARCHAR2(20 BYTE), 
	"STAFF_ID_FK" VARCHAR2(20 BYTE), 
	"LINE1" VARCHAR2(100 BYTE), 
	"LINE2" VARCHAR2(100 BYTE), 
	"ZIP_POST_CODE" VARCHAR2(10 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"STATE_PROVINCE " VARCHAR2(20 BYTE), 
	"COUNTRY" VARCHAR2(20 BYTE), 
	"OTHER_DETAIL" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER_TYPE
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."CUSTOMER_TYPE" 
   (	"CUSTOMER_TYPE_ID" VARCHAR2(20 BYTE), 
	"CUSTOMER_TYPE_DESC" VARCHAR2(50 BYTE), 
	"OTHER_DETAIL" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BRANCH
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."BRANCH" 
   (	"SORT_CODE" VARCHAR2(20 BYTE), 
	"TEL" VARCHAR2(20 BYTE), 
	"BANK_ID_FK" VARCHAR2(20 BYTE), 
	"STAFF-ID-FK" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICE
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."SERVICE" 
   (	"SERVICE_ID" VARCHAR2(20 BYTE), 
	"CUSTOMER_ID_FK" VARCHAR2(20 BYTE), 
	"STAFF_ID" VARCHAR2(20 BYTE), 
	"SERVICE_DESC" VARCHAR2(100 BYTE), 
	"OTHER_DESC" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICE_REQUEST_OUTCOME
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."SERVICE_REQUEST_OUTCOME" 
   (	"SVC_REQ_OUT_ID" VARCHAR2(20 BYTE), 
	"SVC_REQ_OUT_DESC" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER_SERVICE_REQUEST
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."CUSTOMER_SERVICE_REQUEST" 
   (	"CUST_SVC_REQ_ID" VARCHAR2(20 BYTE), 
	"SVC_REQ_OUT_ID_FK" VARCHAR2(20 BYTE), 
	"CUSTOMER_ID_FK" VARCHAR2(20 BYTE), 
	"SVC_ID_FK" VARCHAR2(20 BYTE), 
	"SVC_REQ_DATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STAFF_TYPE
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."STAFF_TYPE" 
   (	"STAFF_TYPE_ID" VARCHAR2(20 BYTE), 
	"STAFF_TYPE_DESC" VARCHAR2(20 BYTE), 
	"OTHER-DETAIL" VARCHAR2(20 BYTE), 
	"ROLE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LOG_BOOK
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."LOG_BOOK" 
   (	"LOG_BOOK_ID" VARCHAR2(20 BYTE), 
	"BAL_HISTORY_ID_FK" VARCHAR2(20 BYTE), 
	"ACCOUNT_ID" VARCHAR2(20 BYTE), 
	"OTHER_DETAIL" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSACTION_TYPE
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."TRANSACTION_TYPE" 
   (	"TRANS_TYPE_ID" VARCHAR2(20 BYTE), 
	"TRANS_DESC" VARCHAR2(50 BYTE), 
	"OTHER_DETAIL" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSACTION
--------------------------------------------------------

  CREATE TABLE "TESTUSER3"."TRANSACTION" 
   (	"TRANS_ID" VARCHAR2(20 BYTE), 
	"TRANS_TYPE_ID_FK" VARCHAR2(20 BYTE), 
	"ACCOUNT_ID_FK" VARCHAR2(20 BYTE), 
	"LOG_BOOK_ID_FK" VARCHAR2(20 BYTE), 
	"TRANS_DATE" DATE, 
	"TRANS_AMOUNT" FLOAT(126), 
	"TRANS_DESC" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;

---------------------------------------------------
--   DATA FOR TABLE BANK
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.BANK
Insert into TESTUSER3.BANK (BANK_ID,BANK_NAME) values ('1','Barclays');
Insert into TESTUSER3.BANK (BANK_ID,BANK_NAME) values ('2','Loyds TSB');
Insert into TESTUSER3.BANK (BANK_ID,BANK_NAME) values ('3','NatWest');

---------------------------------------------------
--   END DATA FOR TABLE BANK
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE CUSTOMER
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.CUSTOMER
Insert into TESTUSER3.CUSTOMER (CUSTOMER_ID,CUSTOMER_TYPE_ID,SSN,FIRST_NAME,LAST_NAME,PHONE,BIRTH_DATE,EMAIL,DATE_JOIN,PASSWORD) values ('1','1','dkf76839dc','Sarfraz','Ahmad','07797687688',to_date('23-DEC-85','DD-MON-RR'),null,null,null);

---------------------------------------------------
--   END DATA FOR TABLE CUSTOMER
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE LOG_BOOK
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.LOG_BOOK
Insert into TESTUSER3.LOG_BOOK (LOG_BOOK_ID,BAL_HISTORY_ID_FK,ACCOUNT_ID,OTHER_DETAIL) values ('1','1','1',null);

---------------------------------------------------
--   END DATA FOR TABLE LOG_BOOK
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE SERVICE
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.SERVICE
Insert into TESTUSER3.SERVICE (SERVICE_ID,CUSTOMER_ID_FK,STAFF_ID,SERVICE_DESC,OTHER_DESC) values ('1','1','1','Send Cheque Book',null);

---------------------------------------------------
--   END DATA FOR TABLE SERVICE
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE ACCOUNT
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.ACCOUNT
Insert into TESTUSER3.ACCOUNT (ACCOUNT_ID,BRANCH_SORTCODE_FK,ACCOUNT_TYPE_ID_FK,STAFF_ID_FK,ACCOUNT_NAME,BALANCE,DATE_OPENED,DATE_CLOSED) values ('1','1','1','1','MR S AHMAD',0,to_date('26-OCT-09','DD-MON-RR'),null);

---------------------------------------------------
--   END DATA FOR TABLE ACCOUNT
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE ADDRESS_TYPE
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.ADDRESS_TYPE
Insert into TESTUSER3.ADDRESS_TYPE (ADDRESS_TYPE_ID,ADDRESS_TYPE_DESC,OTHER_DETAIL) values ('1','Home',null);
Insert into TESTUSER3.ADDRESS_TYPE (ADDRESS_TYPE_ID,ADDRESS_TYPE_DESC,OTHER_DETAIL) values ('2','Office',null);

---------------------------------------------------
--   END DATA FOR TABLE ADDRESS_TYPE
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE ACCOUNT_TYPE
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.ACCOUNT_TYPE
Insert into TESTUSER3.ACCOUNT_TYPE (ACCOUNT_TYPE_ID,OVERDRAF_LIMIT,OTHER_DETAIL,INTEREST_RATE,ACCOUNT_DESC) values ('1',7,null,null,'Current Account');
Insert into TESTUSER3.ACCOUNT_TYPE (ACCOUNT_TYPE_ID,OVERDRAF_LIMIT,OTHER_DETAIL,INTEREST_RATE,ACCOUNT_DESC) values ('2',5,null,null,'Savings Account');

---------------------------------------------------
--   END DATA FOR TABLE ACCOUNT_TYPE
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE CUSTOMER_SERVICE_REQUEST
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.CUSTOMER_SERVICE_REQUEST
Insert into TESTUSER3.CUSTOMER_SERVICE_REQUEST (CUST_SVC_REQ_ID,SVC_REQ_OUT_ID_FK,CUSTOMER_ID_FK,SVC_ID_FK,SVC_REQ_DATE) values ('1','1','1','1',to_date('26-OCT-09','DD-MON-RR'));

---------------------------------------------------
--   END DATA FOR TABLE CUSTOMER_SERVICE_REQUEST
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE STAFF_TYPE
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.STAFF_TYPE
Insert into TESTUSER3.STAFF_TYPE (STAFF_TYPE_ID,STAFF_TYPE_DESC,"OTHER-DETAIL",ROLE) values ('1','Cashier',null,'Permanent');
Insert into TESTUSER3.STAFF_TYPE (STAFF_TYPE_ID,STAFF_TYPE_DESC,"OTHER-DETAIL",ROLE) values ('2','Accountant',null,'Part Time');

---------------------------------------------------
--   END DATA FOR TABLE STAFF_TYPE
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE TRANSACTION
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.TRANSACTION
Insert into TESTUSER3.TRANSACTION (TRANS_ID,TRANS_TYPE_ID_FK,ACCOUNT_ID_FK,LOG_BOOK_ID_FK,TRANS_DATE,TRANS_AMOUNT,TRANS_DESC) values ('1','1','1','1',to_date('26-OCT-09','DD-MON-RR'),20.4,'Card purchase at Turkish merchant store');
Insert into TESTUSER3.TRANSACTION (TRANS_ID,TRANS_TYPE_ID_FK,ACCOUNT_ID_FK,LOG_BOOK_ID_FK,TRANS_DATE,TRANS_AMOUNT,TRANS_DESC) values ('2','1','1','1',to_date('22-DEC-08','DD-MON-RR'),21.11,'Card purchase from Amazon');

---------------------------------------------------
--   END DATA FOR TABLE TRANSACTION
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE STAFF
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.STAFF
Insert into TESTUSER3.STAFF (STAFF_ID,STAFF_TYPE_ID_FK,FIRST_NAME,LAST_NAME,PASSWORD,BIRTH_DATE,PHONE,OTHER_DETAIL) values ('1','1','George',' Philp','abc',to_date('06-OCT-74','DD-MON-RR'),'07778653465',null);
Insert into TESTUSER3.STAFF (STAFF_ID,STAFF_TYPE_ID_FK,FIRST_NAME,LAST_NAME,PASSWORD,BIRTH_DATE,PHONE,OTHER_DETAIL) values ('2','2','Bill','Katrin','xyz',null,null,null);

---------------------------------------------------
--   END DATA FOR TABLE STAFF
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE SERVICE_REQUEST_OUTCOME
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.SERVICE_REQUEST_OUTCOME
Insert into TESTUSER3.SERVICE_REQUEST_OUTCOME (SVC_REQ_OUT_ID,SVC_REQ_OUT_DESC) values ('1','Completed');
Insert into TESTUSER3.SERVICE_REQUEST_OUTCOME (SVC_REQ_OUT_ID,SVC_REQ_OUT_DESC) values ('2','Incomplete');
Insert into TESTUSER3.SERVICE_REQUEST_OUTCOME (SVC_REQ_OUT_ID,SVC_REQ_OUT_DESC) values ('3','Cancelled');

---------------------------------------------------
--   END DATA FOR TABLE SERVICE_REQUEST_OUTCOME
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE BRANCH
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.BRANCH
Insert into TESTUSER3.BRANCH (SORT_CODE,TEL,BANK_ID_FK,"STAFF-ID-FK") values ('23-67-89','08456789876','1','1');
Insert into TESTUSER3.BRANCH (SORT_CODE,TEL,BANK_ID_FK,"STAFF-ID-FK") values ('33-67-98','08007887987','3','2');

---------------------------------------------------
--   END DATA FOR TABLE BRANCH
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE CUSTOMER_TYPE
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.CUSTOMER_TYPE
Insert into TESTUSER3.CUSTOMER_TYPE (CUSTOMER_TYPE_ID,CUSTOMER_TYPE_DESC,OTHER_DETAIL) values ('1','Entrepreneur',null);

---------------------------------------------------
--   END DATA FOR TABLE CUSTOMER_TYPE
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE ADDRESS
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.ADDRESS
Insert into TESTUSER3.ADDRESS (ADDRESS_ID,ADDRESS_TYPE_ID_FK,BANK_ID_FK,CUSTOMER_ID_FK,STAFF_ID_FK,LINE1,LINE2,ZIP_POST_CODE,CITY,"STATE_PROVINCE ",COUNTRY,OTHER_DETAIL) values ('1','1','1','1','1','17 Queenstown Road','Leyton','SW8 3RX','London',null,'UK',null);

---------------------------------------------------
--   END DATA FOR TABLE ADDRESS
---------------------------------------------------

---------------------------------------------------
--   DATA FOR TABLE TRANSACTION_TYPE
--   FILTER = none used
---------------------------------------------------
REM INSERTING into TESTUSER3.TRANSACTION_TYPE
Insert into TESTUSER3.TRANSACTION_TYPE (TRANS_TYPE_ID,TRANS_DESC,OTHER_DETAIL) values ('1','Cash Withdrawl',null);
Insert into TESTUSER3.TRANSACTION_TYPE (TRANS_TYPE_ID,TRANS_DESC,OTHER_DETAIL) values ('2','Cheque Withdrawl',null);
Insert into TESTUSER3.TRANSACTION_TYPE (TRANS_TYPE_ID,TRANS_DESC,OTHER_DETAIL) values ('3','Cash Deposit',null);
Insert into TESTUSER3.TRANSACTION_TYPE (TRANS_TYPE_ID,TRANS_DESC,OTHER_DETAIL) values ('4','eTransfer Credit',null);
Insert into TESTUSER3.TRANSACTION_TYPE (TRANS_TYPE_ID,TRANS_DESC,OTHER_DETAIL) values ('5','eTransfer Debit',null);
Insert into TESTUSER3.TRANSACTION_TYPE (TRANS_TYPE_ID,TRANS_DESC,OTHER_DETAIL) values ('6','Cheque Deposit',null);

---------------------------------------------------
--   END DATA FOR TABLE TRANSACTION_TYPE
---------------------------------------------------
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_PK" PRIMARY KEY ("ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TESTUSER3"."ACCOUNT" MODIFY ("ACCOUNT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."ACCOUNT" MODIFY ("BRANCH_SORTCODE_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."ACCOUNT" MODIFY ("ACCOUNT_TYPE_ID_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."ACCOUNT" MODIFY ("STAFF_ID_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."ACCOUNT" MODIFY ("ACCOUNT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCOUNT_TYPE
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."ACCOUNT_TYPE" ADD CONSTRAINT "ACCOUNT_TYPE_PK" PRIMARY KEY ("ACCOUNT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TESTUSER3"."ACCOUNT_TYPE" MODIFY ("ACCOUNT_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."ACCOUNT_TYPE" MODIFY ("ACCOUNT_DESC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."ADDRESS" MODIFY ("ADDRESS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."ADDRESS" MODIFY ("ADDRESS_TYPE_ID_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."ADDRESS" MODIFY ("BANK_ID_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."ADDRESS" MODIFY ("CUSTOMER_ID_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."ADDRESS" MODIFY ("STAFF_ID_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."ADDRESS" MODIFY ("LINE1" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."ADDRESS" MODIFY ("ZIP_POST_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."ADDRESS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADDRESS_TYPE
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."ADDRESS_TYPE" ADD CONSTRAINT "ADDRESS_TYPE_PK" PRIMARY KEY ("ADDRESS_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TESTUSER3"."ADDRESS_TYPE" MODIFY ("ADDRESS_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."ADDRESS_TYPE" MODIFY ("ADDRESS_TYPE_DESC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BANK
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."BANK" ADD CONSTRAINT "BANK_PK" PRIMARY KEY ("BANK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TESTUSER3"."BANK" MODIFY ("BANK_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."BANK" MODIFY ("BANK_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BRANCH
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."BRANCH" ADD CONSTRAINT "BRANCH_PK" PRIMARY KEY ("SORT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TESTUSER3"."BRANCH" MODIFY ("SORT_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."BRANCH" MODIFY ("TEL" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."BRANCH" MODIFY ("BANK_ID_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."BRANCH" MODIFY ("STAFF-ID-FK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TESTUSER3"."CUSTOMER" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."CUSTOMER" MODIFY ("CUSTOMER_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."CUSTOMER" MODIFY ("SSN" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."CUSTOMER" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."CUSTOMER" MODIFY ("LAST_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER_SERVICE_REQUEST
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."CUSTOMER_SERVICE_REQUEST" ADD CONSTRAINT "CUSTOMER_SERVICE_REQUEST_PK" PRIMARY KEY ("CUST_SVC_REQ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TESTUSER3"."CUSTOMER_SERVICE_REQUEST" MODIFY ("CUST_SVC_REQ_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."CUSTOMER_SERVICE_REQUEST" MODIFY ("SVC_REQ_OUT_ID_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."CUSTOMER_SERVICE_REQUEST" MODIFY ("CUSTOMER_ID_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."CUSTOMER_SERVICE_REQUEST" MODIFY ("SVC_ID_FK" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CUSTOMER_TYPE
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."CUSTOMER_TYPE" ADD CONSTRAINT "CUSTOMER_TYPE_PK" PRIMARY KEY ("CUSTOMER_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TESTUSER3"."CUSTOMER_TYPE" MODIFY ("CUSTOMER_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."CUSTOMER_TYPE" MODIFY ("CUSTOMER_TYPE_DESC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOG_BOOK
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."LOG_BOOK" ADD CONSTRAINT "LOG_BOOK_PK" PRIMARY KEY ("LOG_BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TESTUSER3"."LOG_BOOK" MODIFY ("LOG_BOOK_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."LOG_BOOK" MODIFY ("BAL_HISTORY_ID_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."LOG_BOOK" MODIFY ("ACCOUNT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."SERVICE" ADD CONSTRAINT "SERVICE_PK" PRIMARY KEY ("SERVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TESTUSER3"."SERVICE" MODIFY ("SERVICE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."SERVICE" MODIFY ("CUSTOMER_ID_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."SERVICE" MODIFY ("STAFF_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."SERVICE" MODIFY ("SERVICE_DESC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE_REQUEST_OUTCOME
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."SERVICE_REQUEST_OUTCOME" ADD CONSTRAINT "SERVICE_REQUEST_OUTCOME_PK" PRIMARY KEY ("SVC_REQ_OUT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TESTUSER3"."SERVICE_REQUEST_OUTCOME" MODIFY ("SVC_REQ_OUT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."SERVICE_REQUEST_OUTCOME" MODIFY ("SVC_REQ_OUT_DESC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."STAFF" ADD CONSTRAINT "STAFF_PK" PRIMARY KEY ("STAFF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TESTUSER3"."STAFF" MODIFY ("STAFF_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."STAFF" MODIFY ("STAFF_TYPE_ID_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."STAFF" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."STAFF" MODIFY ("LAST_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STAFF_TYPE
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."STAFF_TYPE" ADD CONSTRAINT "STAFF_TYPE_PK" PRIMARY KEY ("STAFF_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "TESTUSER3"."STAFF_TYPE" MODIFY ("STAFF_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."STAFF_TYPE" MODIFY ("STAFF_TYPE_DESC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."TRANSACTION" MODIFY ("TRANS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."TRANSACTION" MODIFY ("TRANS_TYPE_ID_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."TRANSACTION" MODIFY ("ACCOUNT_ID_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."TRANSACTION" MODIFY ("LOG_BOOK_ID_FK" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."TRANSACTION" MODIFY ("TRANS_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."TRANSACTION" MODIFY ("TRANS_AMOUNT" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."TRANSACTION" MODIFY ("TRANS_DESC" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."TRANSACTION" ADD CONSTRAINT "TRANSACTION_PK" PRIMARY KEY ("TRANS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACTION_TYPE
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."TRANSACTION_TYPE" MODIFY ("TRANS_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."TRANSACTION_TYPE" MODIFY ("TRANS_DESC" NOT NULL ENABLE);
 
  ALTER TABLE "TESTUSER3"."TRANSACTION_TYPE" ADD CONSTRAINT "TRANSACTION_TYPE_PK" PRIMARY KEY ("TRANS_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  DDL for Index ACCOUNT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."ACCOUNT_PK" ON "TESTUSER3"."ACCOUNT" ("ACCOUNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ACCOUNT_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."ACCOUNT_TYPE_PK" ON "TESTUSER3"."ACCOUNT_TYPE" ("ACCOUNT_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADDRESS_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."ADDRESS_TYPE_PK" ON "TESTUSER3"."ADDRESS_TYPE" ("ADDRESS_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BANK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."BANK_PK" ON "TESTUSER3"."BANK" ("BANK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index BRANCH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."BRANCH_PK" ON "TESTUSER3"."BRANCH" ("SORT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."CUSTOMER_PK" ON "TESTUSER3"."CUSTOMER" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_SERVICE_REQUEST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."CUSTOMER_SERVICE_REQUEST_PK" ON "TESTUSER3"."CUSTOMER_SERVICE_REQUEST" ("CUST_SVC_REQ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."CUSTOMER_TYPE_PK" ON "TESTUSER3"."CUSTOMER_TYPE" ("CUSTOMER_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LOG_BOOK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."LOG_BOOK_PK" ON "TESTUSER3"."LOG_BOOK" ("LOG_BOOK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SERVICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."SERVICE_PK" ON "TESTUSER3"."SERVICE" ("SERVICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SERVICE_REQUEST_OUTCOME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."SERVICE_REQUEST_OUTCOME_PK" ON "TESTUSER3"."SERVICE_REQUEST_OUTCOME" ("SVC_REQ_OUT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STAFF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."STAFF_PK" ON "TESTUSER3"."STAFF" ("STAFF_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STAFF_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."STAFF_TYPE_PK" ON "TESTUSER3"."STAFF_TYPE" ("STAFF_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."TABLE1_PK" ON "TESTUSER3"."ADDRESS" ("ADDRESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSACTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."TRANSACTION_PK" ON "TESTUSER3"."TRANSACTION" ("TRANS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSACTION_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSER3"."TRANSACTION_TYPE_PK" ON "TESTUSER3"."TRANSACTION_TYPE" ("TRANS_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_ACCOUNT_TYPE_FK1" FOREIGN KEY ("ACCOUNT_TYPE_ID_FK")
	  REFERENCES "TESTUSER3"."ACCOUNT_TYPE" ("ACCOUNT_TYPE_ID") ENABLE;
 
  ALTER TABLE "TESTUSER3"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_STAFF_FK1" FOREIGN KEY ("STAFF_ID_FK")
	  REFERENCES "TESTUSER3"."STAFF" ("STAFF_ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."ADDRESS" ADD CONSTRAINT "ADDRESS_ADDRESS_TYPE_FK1" FOREIGN KEY ("ADDRESS_TYPE_ID_FK")
	  REFERENCES "TESTUSER3"."ADDRESS_TYPE" ("ADDRESS_TYPE_ID") ENABLE;
 
  ALTER TABLE "TESTUSER3"."ADDRESS" ADD CONSTRAINT "ADDRESS_BANK_FK1" FOREIGN KEY ("BANK_ID_FK")
	  REFERENCES "TESTUSER3"."BANK" ("BANK_ID") ENABLE;
 
  ALTER TABLE "TESTUSER3"."ADDRESS" ADD CONSTRAINT "ADDRESS_CUSTOMER_FK1" FOREIGN KEY ("CUSTOMER_ID_FK")
	  REFERENCES "TESTUSER3"."CUSTOMER" ("CUSTOMER_ID") ENABLE;
 
  ALTER TABLE "TESTUSER3"."ADDRESS" ADD CONSTRAINT "ADDRESS_STAFF_FK1" FOREIGN KEY ("STAFF_ID_FK")
	  REFERENCES "TESTUSER3"."STAFF" ("STAFF_ID") ENABLE;


--------------------------------------------------------
--  Ref Constraints for Table BRANCH
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."BRANCH" ADD CONSTRAINT "BANK_ID_FK" FOREIGN KEY ("BANK_ID_FK")
	  REFERENCES "TESTUSER3"."BANK" ("BANK_ID") ENABLE;
 
  ALTER TABLE "TESTUSER3"."BRANCH" ADD CONSTRAINT "BRANCH_STAFF_FK1" FOREIGN KEY ("STAFF-ID-FK")
	  REFERENCES "TESTUSER3"."STAFF" ("STAFF_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_CUSTOMER_TYPE_FK1" FOREIGN KEY ("CUSTOMER_TYPE_ID")
	  REFERENCES "TESTUSER3"."CUSTOMER_TYPE" ("CUSTOMER_TYPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CUSTOMER_SERVICE_REQUEST
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."CUSTOMER_SERVICE_REQUEST" ADD CONSTRAINT "CUSTOMER_SERVICE_REQUEST__FK1" FOREIGN KEY ("SVC_REQ_OUT_ID_FK")
	  REFERENCES "TESTUSER3"."SERVICE_REQUEST_OUTCOME" ("SVC_REQ_OUT_ID") ENABLE;
 
  ALTER TABLE "TESTUSER3"."CUSTOMER_SERVICE_REQUEST" ADD CONSTRAINT "CUSTOMER_SERVICE_REQUEST__FK2" FOREIGN KEY ("CUSTOMER_ID_FK")
	  REFERENCES "TESTUSER3"."CUSTOMER" ("CUSTOMER_ID") ENABLE;
 
  ALTER TABLE "TESTUSER3"."CUSTOMER_SERVICE_REQUEST" ADD CONSTRAINT "CUSTOMER_SERVICE_REQUEST__FK3" FOREIGN KEY ("SVC_ID_FK")
	  REFERENCES "TESTUSER3"."SERVICE" ("SERVICE_ID") ENABLE;


--------------------------------------------------------
--  Ref Constraints for Table SERVICE
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."SERVICE" ADD CONSTRAINT "SERVICE_CUSTOMER_FK1" FOREIGN KEY ("CUSTOMER_ID_FK")
	  REFERENCES "TESTUSER3"."CUSTOMER" ("CUSTOMER_ID") ENABLE;
 
  ALTER TABLE "TESTUSER3"."SERVICE" ADD CONSTRAINT "SERVICE_STAFF_FK1" FOREIGN KEY ("STAFF_ID")
	  REFERENCES "TESTUSER3"."STAFF" ("STAFF_ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."STAFF" ADD CONSTRAINT "STAFF_STAFF_TYPE_FK1" FOREIGN KEY ("STAFF_TYPE_ID_FK")
	  REFERENCES "TESTUSER3"."STAFF_TYPE" ("STAFF_TYPE_ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "TESTUSER3"."TRANSACTION" ADD CONSTRAINT "TRANSACTION_ACCOUNT_FK" FOREIGN KEY ("ACCOUNT_ID_FK")
	  REFERENCES "TESTUSER3"."ACCOUNT" ("ACCOUNT_ID") ENABLE;
 
  ALTER TABLE "TESTUSER3"."TRANSACTION" ADD CONSTRAINT "TRANSACTION_LOG_BOOK_FK" FOREIGN KEY ("LOG_BOOK_ID_FK")
	  REFERENCES "TESTUSER3"."LOG_BOOK" ("LOG_BOOK_ID") ENABLE;
 
  ALTER TABLE "TESTUSER3"."TRANSACTION" ADD CONSTRAINT "TRANSACTION_TRANSACTION_T_FK1" FOREIGN KEY ("TRANS_TYPE_ID_FK")
	  REFERENCES "TESTUSER3"."TRANSACTION_TYPE" ("TRANS_TYPE_ID") ENABLE;

